spring:
  application:
    name: refit
  profiles:
    active: "${SPRING_PROFILES_ACTIVE}"
    group:
      test: "test"
      local: "local, datasource, swagger"
      dev: "dev, datasource, swagger"
    include:
      - s3
      - auth

server:
  tomcat:
    uri-encoding: UTF-8

springdoc:
  swagger-ui:
    display-operation-id: true
