springdoc:
  swagger-ui:
    defaultModelsExpandDepth: 0
    operationsSorter: alpha
    display-operation-id: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
