spring:
  auth:
    using-https: ${AUTH_USING_HTTPS}
    url:
      # TODO: public한 API 경로가 더 있는지 검토 필요
      sign-up: "/user/signup"
      whitelists:
        - "/auth/login/**"
        - "/auth/reissue"
        - "/swagger-ui/**"
        - "/v3/api-docs/**"
    jwt:
      secret: "${JWT_SECRET}"
      token-expiration:
        access-token: ${JWT_ACCESS_TOKEN_EXPIRATION}
        refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION}
    oauth2:
      state-expiration: ${OAUTH2_STATE_EXPIRATION}
      google:
        client-id: "${GOOGLE_CLIENT_ID}"
        client-secret: "${GOOGLE_CLIENT_SECRET}"
        redirect-path: "${GOOGLE_REDIRECT_PATH}"
        scope:
          - openid
          - profile
          - email
