spring:
  application:
    name: refit
  profiles:
    active: "${SPRING_PROFILES_ACTIVE}"
    group:
      test: "test"
      local: "local, datasource, auth"
      dev: "dev, datasource, auth"
    include:
      - s3

server:
  tomcat:
    uri-encoding: UTF-8
