spring:
  auth:
    # TODO: public한 API 경로가 더 있는지 검토 필요
    whitelist-api-urls:
      - /auth/login/**
      - /swagger-ui/**
      - /v3/api-docs/**

    jwt:
      secret: "${JWT_SECRET}"
      validity-in-milliseconds: "${JWT_VALIDITY_IN_MILLISECONDS}"

    google:
      client-id: "${GOOGLE_CLIENT_ID}"
      client-secret: "${GOOGLE_CLIENT_SECRET}"
      redirect-uri: "${GOOGLE_REDIRECT_URI}"
      scope:
        - profile
        - email