spring:
  ai:
    gemini:
      api-key: "${GEMINI_API_KEY}"
      prompt-path: "${GEMINI_PROMPT_PATH}"
    vectorstore:
      vector-size: ${VECTOR_STORE_VECTOR_SIZE}
      qdrant:
        host: "${QDRANT_HOST}"
        port: ${QDRANT_PORT}
        collection-base-name: "${QDRANT_COLLECTION_BASE_NAME}"
        distance: "${QDRANT_DISTANCE}"
