on:
  pull_request:
    branches:
      - dev
    paths:
      - "backend/**"

jobs:
  build_application:
    name: test application
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Test Project
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      #      - name: Set Redis
      #        run: docker compose -f docker-compose-test.yml up -d

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0'

      - name: Set Permission to gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle Wrapper
        run: ./gradlew check
